"""Alter table book add finished column

Revision ID: c87d2cc4a228
Revises: d9b6af6a4b90
Create Date: 2024-01-05 09:33:46.653011

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c87d2cc4a228'
down_revision = 'd9b6af6a4b90'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('finished', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.drop_column('finished')

    # ### end Alembic commands ###
